import type { ProjectTemplate } from '@/types/builder';

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'ecommerce-pro',
    name: 'E-Commerce Pro',
    category: 'ecommerce',
    description: 'Full storefront with product grid, cart, checkout, and Stripe payments.',
    icon: 'ShoppingBag',
    prompt: 'An e-commerce store for handmade products with product grid, cart, Stripe checkout, and user accounts',
    features: ['Shopping cart', 'In-app payments', 'User authentication', 'Search', 'Push notifications'],
    colorScheme: { primary: '#ea580c', secondary: '#f59e0b', accent: '#dc2626', background: '#fff7ed', surface: '#ffffff', text: '#1c1917' },
    screenCount: 6,
    tags: ['Shop', 'Payments', 'Auth'],
  },
  {
    id: 'fitness-tracker',
    name: 'Fitness Tracker',
    category: 'fitness',
    description: 'Workout tracker with activity rings, exercise library, and progress charts.',
    icon: 'Dumbbell',
    prompt: 'A fitness tracking app with workout logs, calorie counting, activity charts, and reminders',
    features: ['Activity tracking', 'Charts & analytics', 'Push notifications', 'Offline support'],
    colorScheme: { primary: '#dc2626', secondary: '#f97316', accent: '#16a34a', background: '#fef2f2', surface: '#ffffff', text: '#450a0a' },
    screenCount: 5,
    tags: ['Health', 'Charts', 'Notifications'],
  },
  {
    id: 'social-app',
    name: 'Social Network',
    category: 'social',
    description: 'Social feed with posts, likes, comments, stories, and real-time chat.',
    icon: 'Users',
    prompt: 'A social network app with feed, posts, likes, comments, stories, and real-time chat',
    features: ['Real-time chat', 'Social sharing', 'User authentication', 'Camera & uploads', 'Push notifications'],
    colorScheme: { primary: '#db2777', secondary: '#f43f5e', accent: '#8b5cf6', background: '#fdf2f8', surface: '#ffffff', text: '#500724' },
    screenCount: 7,
    tags: ['Social', 'Chat', 'Media'],
  },
  {
    id: 'task-manager',
    name: 'Task Manager',
    category: 'productivity',
    description: 'Kanban-style task manager with categories, reminders, and team collaboration.',
    icon: 'CheckSquare',
    prompt: 'A task manager app with categories, reminders, kanban board, and user collaboration',
    features: ['User authentication', 'Push notifications', 'Offline support', 'Search'],
    colorScheme: { primary: '#2563eb', secondary: '#0ea5e9', accent: '#f59e0b', background: '#f8fafc', surface: '#ffffff', text: '#0f172a' },
    screenCount: 5,
    tags: ['Productivity', 'Kanban', 'Teams'],
  },
  {
    id: 'finance-app',
    name: 'Budget Tracker',
    category: 'finance',
    description: 'Personal finance manager with expense tracking, budgets, and visual analytics.',
    icon: 'Wallet',
    prompt: 'A budget tracker app with expense categories, charts, budget goals, and account sync',
    features: ['Charts & analytics', 'Expense categorization', 'User authentication', 'Push notifications'],
    colorScheme: { primary: '#16a34a', secondary: '#22c55e', accent: '#0ea5e9', background: '#f0fdf4', surface: '#ffffff', text: '#052e16' },
    screenCount: 5,
    tags: ['Finance', 'Charts', 'Budget'],
  },
  {
    id: 'chat-app',
    name: 'Chat Messenger',
    category: 'communication',
    description: 'Real-time messaging app with conversations, media sharing, and voice messages.',
    icon: 'MessageCircle',
    prompt: 'A chat app with conversations, media sharing, voice messages, and group chats',
    features: ['Real-time chat', 'Camera & uploads', 'Push notifications', 'User authentication'],
    colorScheme: { primary: '#059669', secondary: '#10b981', accent: '#6366f1', background: '#f0fdf4', surface: '#ffffff', text: '#064e3b' },
    screenCount: 4,
    tags: ['Chat', 'Real-time', 'Media'],
  },
  {
    id: 'recipe-app',
    name: 'Recipe App',
    category: 'lifestyle',
    description: 'Recipe discovery with search, cooking timers, and meal planning.',
    icon: 'ChefHat',
    prompt: 'A recipe app with search, cooking timers, meal planning, and grocery lists',
    features: ['Search', 'Push notifications', 'Offline support'],
    colorScheme: { primary: '#d97706', secondary: '#f59e0b', accent: '#84cc16', background: '#fffbeb', surface: '#ffffff', text: '#451a03' },
    screenCount: 4,
    tags: ['Food', 'Search', 'Timer'],
  },
  {
    id: 'booking-app',
    name: 'Booking App',
    category: 'service',
    description: 'Appointment booking with calendar, reminders, and payment integration.',
    icon: 'Calendar',
    prompt: 'A booking app with calendar, appointment scheduling, reminders, and payments',
    features: ['In-app payments', 'Push notifications', 'User authentication', 'Maps & location'],
    colorScheme: { primary: '#0891b2', secondary: '#06b6d4', accent: '#f59e0b', background: '#ecfeff', surface: '#ffffff', text: '#083344' },
    screenCount: 5,
    tags: ['Booking', 'Calendar', 'Payments'],
  },
  {
    id: 'learning-app',
    name: 'Learning Platform',
    category: 'education',
    description: 'Online courses with video lessons, quizzes, and progress tracking.',
    icon: 'GraduationCap',
    prompt: 'A learning platform with courses, video lessons, quizzes, and progress tracking',
    features: ['User authentication', 'Charts & analytics', 'Push notifications', 'Offline support'],
    colorScheme: { primary: '#1d4ed8', secondary: '#2563eb', accent: '#f59e0b', background: '#eff6ff', surface: '#ffffff', text: '#172554' },
    screenCount: 6,
    tags: ['Education', 'Video', 'Quizzes'],
  },
  {
    id: 'news-app',
    name: 'News Reader',
    category: 'media',
    description: 'News aggregator with categories, bookmarks, and offline reading.',
    icon: 'Newspaper',
    prompt: 'A news reader app with categories, bookmarks, offline reading, and push alerts',
    features: ['Push notifications', 'Offline support', 'Search'],
    colorScheme: { primary: '#1e293b', secondary: '#475569', accent: '#dc2626', background: '#f1f5f9', surface: '#ffffff', text: '#020617' },
    screenCount: 4,
    tags: ['News', 'Offline', 'Bookmark'],
  },
  {
    id: 'music-app',
    name: 'Music Player',
    category: 'media',
    description: 'Music streaming with playlists, player controls, and offline downloads.',
    icon: 'Music',
    prompt: 'A music player app with playlists, streaming, offline downloads, and lyrics',
    features: ['Offline support', 'Search', 'Push notifications'],
    colorScheme: { primary: '#9333ea', secondary: '#a855f7', accent: '#f43f5e', background: '#faf5ff', surface: '#ffffff', text: '#3b0764' },
    screenCount: 5,
    tags: ['Music', 'Streaming', 'Offline'],
  },
  {
    id: 'habit-tracker',
    name: 'Habit Tracker',
    category: 'productivity',
    description: 'Daily habit tracker with streaks, reminders, and analytics.',
    icon: 'Flame',
    prompt: 'A habit tracker app with daily streaks, reminders, analytics, and goals',
    features: ['Charts & analytics', 'Push notifications', 'Offline support'],
    colorScheme: { primary: '#059669', secondary: '#10b981', accent: '#f59e0b', background: '#ecfdf5', surface: '#ffffff', text: '#022c22' },
    screenCount: 4,
    tags: ['Habits', 'Streaks', 'Analytics'],
  },
];

export const TEMPLATE_CATEGORIES = [
  'all',
  'ecommerce',
  'productivity',
  'social',
  'finance',
  'communication',
  'lifestyle',
  'service',
  'education',
  'media',
];
